#!/bin/sh
exec 2>&1

PERL=/home/babyry/perl5/perlbrew/perls/perl-5.16.3/bin/perl
DAEMON=/home/babyry/BabyryServer/script/daemon/disable_withdraw_user.pl

exec \
  envdir ./env \
  setuidgid babyry \
  $PERL $DAEMON
